# Generated by Django 3.1.1 on 2020-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('address1', models.TextField()),
                ('city', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
