# Generated by Django 3.1.1 on 2020-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_2',
            field=models.TextField(default=None),
        ),
    ]
